### ISSUE TITLE
Why write a newline separately in writer_sink.go func Log()?

### ISSUE THREAD

**Issue by moonese** [pivotal-golang/lager#13]
When reading code, I just wondering why need to append a newline in func Log of writer_sink.go, and why to remove syslog_sink.go? Would you like to tell me detail on these changes?

If I still use syslog sink for example, Log() call will cuase a empty message send to syslog, right?

So my opnion is that if we really need to add a newline, instead of call sink.writer.Write("\n"), use below code will be better?

```
log = append(log, '\n')
sink.writeL.Lock()
sink.writer.Write(log)
sink.writeL.Unlock()
```

**Comment by ematpl** [comment]
Hi, @moonese,

The syslog sink was removed quite a long time ago. I don't know the rationale at the time, but I suspect it was removed because lager exists primarily to serve [diego-release](https://github.com/cloudfoundry-incubator/diego-release), and the syslog sink isn't used there. It's certainly possible to maintain your own version of a syslog-writing sink that conforms to the `lager.Sink` interface, and register an instance of that to your logger as a sink.

I don't think the additional `sink.writer.Write([]byte("\n"))` in the `writerSink` would cause the old `syslogSink` to log an additional line, since they're separate types. Are you actually seeing that behavior in your use of the package?

Thanks,
Eric, CF Runtime Diego PM

**Comment by moonese** [comment]
Hi @ematpl ,

I have checked the git history, and it is really removed quite long ago at 06/2014.

In my situation, I use the way similiar to syslogSink but send log message via tcp to another pc, like below code:
```
sink, err = NewSyslogSink("tcp", "9.91.34.91:5001", "my-tag", DEBUG)
fmt.Println(err)
sink.Log(INFO, []byte("hello"))
sink.Log(INFO, []byte("\n"))
```
in such case, it will do send out two separate packets for each call of sink.Log(), as below packets capture show:
![image](https://cloud.githubusercontent.com/assets/29681/10037808/cd624aea-61ed-11e5-85e5-852da5569f7a.png)

So if the sink is to output to local syslog or file, it will not be the same; but if the output is to another server via tcp/udp, it will have this issue.

If you agree this is an issue, I can submit a PR for this change, or you can also change it.

**Comment by ematpl** [comment]
Hi, @moonese,

Yes, it was removed in commit https://github.com/pivotal-golang/lager/commit/9130418367b0e6e9ff22be7ab06c8f6b9c216601, over a year ago, and fairly early on in the development of the lager package.

I don't quite understand your example: you call `sink.Log` twice, and there are two syslog entries in your packet capture. Those two syslog entries correspond exactly to what you would expect from calling `Info("hello")` and `Info("\n")` on the sink's underlying `syslog.Writer`, given the processing that occurs in the Writer's private `write` method: https://golang.org/src/log/syslog/syslog.go?#L261.

As I mentioned before, the additional `Write([]byte("\n"))` you refer to in [writer_sink.go](https://github.com/pivotal-golang/lager/blob/master/writer_sink.go#L37-L38) is irrelevant to the lager package's now-removed `syslogSink`, since they have entirely different code paths. You could replace [the `"\n"` line in the `writerSink`](https://github.com/pivotal-golang/lager/blob/master/writer_sink.go#L37-L38) with `panic("ka-boom!")`, and if you're using only the `syslogSink`, operate your logging just fine, as you would never hit that panic.

Thanks,
Eric

**Comment by moonese** [comment]
Hi @ematpl ,

I understand what you mean now, and sorry for giving a mis-leading sample code which takes more confusion. 

I double checked and found the problem is that instead of using the original syslogSink which I supposed to be, one of my ex-colleague just uses NewWriterSink in writer_sink.go, and write a new Writer to redirect the messages to other host via tcp. So as I found out in the beginning, the ```sink.writer.Write([]byte("\n")) ``` call will send out an extra packet with "\n" to remote host.

So the problem is that should we consider such kind of use case of NewWriterSink, and to avoid it the way I suggests in the beginning?

Thanks!
Tao

**Comment by tedsuo** [comment]
Closing this issue, as we are shifting lager to OpenTracing, which moves the serialization and transport our of lager.
