### ISSUE TITLE
Improve usability of levelled logging

### ISSUE THREAD

**Issue by glyn** [pivotal-golang/lager#4]
The readme mentions logging levels but only in terms of creating logs. It does not describe how to configure logging at runtime such that only logs of particular levels are output. Without this ability, levels are not so useful. For example, if there are many debug logs, informational messages can be swamped and so it is usual to turn off debug (and possibly info) messages when using a levelled logging system unless debugging is required.

Then when the logging level needs to be increased, e.g. during debugging, turning on debug logging globally often produces too great a volume of logs, so it is usual in logging systems to be able to narrow down the areas of code for which logging is activated.

See, for example, the way the `vmodule` flag of the [glog library](http://godoc.org/github.com/golang/glog) works.

For more general inspiration from a mature logging framework, see Java's [logback](http://logback.qos.ch/manual/index.html).

**Comment by glyn** [comment]
Not sure why this was closed.

**Comment by tedsuo** [comment]
Sorry, thought this was a dead topic. 

We are moving to OpenTracing, so the details in this discussion will be changing. In OpenTracing, like X-Trace and Dapper, there is no direct concept of log levels, or of choosing which log levels to write out.  Because there are no standard log levels, we would like to move to a more general concept in OpenTracing of sampling and `sampling_priority`, which allows us to throttle log output while ensuring that important traces are always recorded. Our Debug, Info, and Error logs can map to sampling priorities, and recorders can do whatever implementation specific things they do with that information.  

In the lager package, we will provide a basic tracer implementation that can enable/disable the lowest sampling priority (DEBUG statements), and a test tracer that works with our ginkgo tooling. This recreates our existing tools. But we should be able to start consuming 3rd party tracers, such as tracers that do sampling and log in ZipKin format, as they are added to the OpenTracing community.

**Comment by glyn** [comment]
Thanks for the info.
