### ISSUE TITLE
Sessions and scopes

### ISSUE THREAD

**Issue by tedsuo** [pivotal-golang/lager#7]
# Sessions and scopes

This document proposes Sessions, a scopr or closure for logs.  By identifying when logs start and stop we can derive durations and other useful data points, and create visualizations which will aid in debugging and operation.  

This proposal supercedes the existing Session concept in lager.

## Sessions

Session extends the `Logger` interface in the following manner:

```
type Session interface {
	Logger
	StartSession(name string) Session
	Complete()
	SessionInfo() SessionInfo
}

func StartSession(name string, Logger)Session
```

`StartSession` creates a new session in a nested namespace.  It emits a `start` log upon creation.

`Complete` closes the current session.  Upon close, a `complete` log is emitted.  Any further logging to the session is marked with a `ErrSessionComplete` flag that chug can identify.

`SessionInfo` returns a data object which can be used to serialize session state.  SessionInfo is explained below.

##  SessionInfo

SessionInfo is a struct which can be used to serialize session state.

```
type SessionInfo struct {
	Name string			`json:"name"`
	SessionID string 	`json:"session_id"`
	Data Data 			`json:"data"`
}

func (SessionInfo) NewLogger() Logger
func (SessionInfo) StartSession(name string, Logger) Logger

func NewSessionInfo(Session) SessionInfo

func SessionInfoToHeader(SessionInfo)string
func SessionInfoFromHeader(string) SessionInfo
```

Note that `SessionInfoToHeader` does not write out the logger's `Data` over the wire, as this has the potential to add arbitraty load to our requests.

## Chug Scopes

Once standardized `start` and `complete` logs have been deployed, we can extend the `chug` log visualizer to display `scopes`, groups of sessions laid out side by side.  

Examples of useful side-by-side comparisions:

- repeated calls to the same http endpoint.
- concurrent (overlapping) activity in multiple goroutines.
- sorting by session length to find leaking goroutines 

Another useful visualization would be the nesting of sessions, shown via intentation or "flame graph".  This is a useful view because it mirrors the decision tree in the code, and can help identify where a program is spending it's time.

**Comment by fraenkel** [comment]
I think we are conflating a few things with this concept of a Session or we have a need for something else that is similar to a session but no lifecycle.

If we truly want lifecycle, why not add new lager APIs rather than put it on a session?  Having a Begin/End, Start/Finished, whatever is a nit.

How do I create a nested namespace but not emit a start log?
If we are truly creating nested sessions, does a Complete() of a parent session close all child sessions as well?

Shouldn't StartSession() return a Session?
What is the purpose of NewSessionInfo() given I have Session.SessionInfo()

The ToHeader/FromHeader seem like a leap.
Why not just support Stringer or TextMarshaler/TextUnmarshaler?

**Comment by tedsuo** [comment]
Closing this issue, in favor of standardizing on OpenTracing to solve these problems: https://github.com/pivotal-golang/lager/issues/18
