### ISSUE TITLE
gosteno vs lager?

### ISSUE THREAD

**Issue by wulonghui** [pivotal-golang/lager#9]
Why use lager instead of gosteno n diego?

**Comment by ematpl** [comment]
Hi, @wulonghui,

Thanks for asking about this, and apologies for the delayed reply.

I haven't used [gosteno](https://github.com/cloudfoundry/gosteno) much myself, but after inspecting the code and the example it seems to maintain a lot of singular global state (a complicated config object and a map of loggers) in order to provide some autowiring of logger instances. Moreover, there seems to be no way to work with these loggers without interacting with this global state: the only provided constructor function for a Logger instance retrieves its config (and potentially the instance itself) from it, and because the Logger struct has unexported fields it is impossible to construct a valid one any other way. Consequently, it is difficult to work with these loggers in test cases, as they inherently attract test pollution that can affect assertions made against them. 

The lager package, on the other hand, relies on no global state: each call of the `NewLogger()` constructor function returns an independent instance that satisfies the `lager.Logger` interface. At that point, whatever log sinks are desired can be attached to the new Logger, and the logger will write its JSON-encoded output to them. 

This behavior makes logging behavior inherently more testable. When we exercise a client of the logger as the subject in a test case, we can pass it a test double conforming to the Logger interface that, instead of writing log output to a global sink, can capture arguments of individual logging calls or can write logs to a local buffer for later inspection in the test case. The lager repo itself provides a `TestLogger` in its `lagertest` subpackage for exactly this purpose.

Additionally, we have found that we benefit during development from making the passage of these loggers explicit in the codebase. Rather than obtaining a logger by name in some potentially unknown state, each object that requires a logger either makes its own or receives a logger from some other object when constructed or when called via a method invocation. We're then also never surprised that a particular object is logging, since we can tell from its dependencies whether it even has access to the logging system. The `NewSession()` method of the Logger interface makes it easy to chain together logger subjects to represent different contexts of execution. In the [diego-release](https://github.com/cloudfoundry-incubator/diego-release) components, we tend to make one top-level logger for the entire component, and then pass it or new sessions on it to the components that need to log.

@tedsuo was primarily responsible for the development of the lager package last year, so if you have other specific questions about its design he may be able to provide more insight about them. 

Thanks,
Eric, CF Runtime Diego PM

**Comment by tedsuo** [comment]
Eric pretty much summed it up. No global state, structured logging only, and execution tracing via Sessions.

There is currently no motion to force existing components off of gosteno, but new components should be started with lager. We suggest that other cloudfoundry components switch to using lager so that they can take advantage of the tooling we have written around lager, such as https://github.com/pivotal-cf-experimental/veritas.

**Comment by wulonghui** [comment]
Thanks for the details.
